---
- name: install patches
  hosts: workstation.lab.example.com
  become: true
  remote_user: root
  tasks:
  - name: install packages
    yum:
      name: vsftpd
      state: latest

  - name:  install dovecot
    yum:
      name: dovecot
      state: latest
